"""
Fixtures e bootstrap de caminhos para execução dos testes automatizados.

Projeto: PINN Thermal 2D
Autores:
    - Josemar Rocha Pedroso
    - Camila Borge
    - Nuccia Carla Arruda de Souza
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = PROJECT_ROOT / "src"
TESTS_DIR = PROJECT_ROOT / "scripts" / "tests"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))
if str(TESTS_DIR) not in sys.path:
    sys.path.insert(1, str(TESTS_DIR))


@pytest.fixture()
def config_guard():
    """Preserva e restaura valores de Config alterados durante cada teste."""
    from config import Config

    tracked = {
        "FDM_NX": Config.FDM_NX,
        "FDM_NY": Config.FDM_NY,
        "FDM_TOL": Config.FDM_TOL,
        "FDM_MAX_ITER": Config.FDM_MAX_ITER,
        "FDM_OMEGA": Config.FDM_OMEGA,
        "DEFAULT_N_INTERIOR": Config.DEFAULT_N_INTERIOR,
        "DEFAULT_N_BOUNDARY": Config.DEFAULT_N_BOUNDARY,
        "DEFAULT_N_DATA": Config.DEFAULT_N_DATA,
        "DEFAULT_N_MIDLINE": Config.DEFAULT_N_MIDLINE,
        "ENABLE_LEFT_IMPORTANCE_SAMPLING": Config.ENABLE_LEFT_IMPORTANCE_SAMPLING,
        "LEFT_IMPORTANCE_FRACTION": Config.LEFT_IMPORTANCE_FRACTION,
        "LEFT_IMPORTANCE_BAND_FRACTION": Config.LEFT_IMPORTANCE_BAND_FRACTION,
        "ENABLE_RIGHT_IMPORTANCE_SAMPLING": Config.ENABLE_RIGHT_IMPORTANCE_SAMPLING,
        "RIGHT_IMPORTANCE_FRACTION": Config.RIGHT_IMPORTANCE_FRACTION,
        "RIGHT_IMPORTANCE_BAND_FRACTION": Config.RIGHT_IMPORTANCE_BAND_FRACTION,
        "RIGHT_DIRICHLET_MULTIPLIER": Config.RIGHT_DIRICHLET_MULTIPLIER,
        "COLLOCATION_AUDIT_ENABLED": Config.COLLOCATION_AUDIT_ENABLED,
        "COLLOCATION_AUDIT_BAND_FRACTION": Config.COLLOCATION_AUDIT_BAND_FRACTION,
        "DEFAULT_LAYERS": list(Config.DEFAULT_LAYERS),
        "DEFAULT_ACTIVATION": Config.DEFAULT_ACTIVATION,
        "INPUT_NORMALIZATION": Config.INPUT_NORMALIZATION,
        "ENABLE_HARD_DIRICHLET_CONSTRAINT": Config.ENABLE_HARD_DIRICHLET_CONSTRAINT,
        "ADAPTIVE_TANH_INIT": Config.ADAPTIVE_TANH_INIT,
        "ADAPTIVE_TANH_MIN_SLOPE": Config.ADAPTIVE_TANH_MIN_SLOPE,
        "DEFAULT_EPOCHS_ADAM": Config.DEFAULT_EPOCHS_ADAM,
        "DEFAULT_EPOCHS_LBFGS": Config.DEFAULT_EPOCHS_LBFGS,
        "DEFAULT_LR": Config.DEFAULT_LR,
        "LBFGS_LR": Config.LBFGS_LR,
        "LBFGS_HISTORY_SIZE": Config.LBFGS_HISTORY_SIZE,
        "LBFGS_LINE_SEARCH_FN": Config.LBFGS_LINE_SEARCH_FN,
        "DEFAULT_W_DATA": Config.DEFAULT_W_DATA,
        "LEFT_DIRICHLET_WEIGHT_MULTIPLIER": Config.LEFT_DIRICHLET_WEIGHT_MULTIPLIER,
        "RIGHT_DIRICHLET_LOSS_MULTIPLIER": Config.RIGHT_DIRICHLET_LOSS_MULTIPLIER,
        "AUTO_BALANCE_DIRICHLET_SIDES": Config.AUTO_BALANCE_DIRICHLET_SIDES,
        "DIRICHLET_SIDE_TARGET_RATIO": Config.DIRICHLET_SIDE_TARGET_RATIO,
        "DIRICHLET_SIDE_RATIO_TOLERANCE": Config.DIRICHLET_SIDE_RATIO_TOLERANCE,
        "RIGHT_DIRICHLET_LOSS_ADAPT_RATE": Config.RIGHT_DIRICHLET_LOSS_ADAPT_RATE,
        "ENABLE_DIRICHLET_NTK_BALANCE": Config.ENABLE_DIRICHLET_NTK_BALANCE,
        "DIRICHLET_NTK_BALANCE_FREQUENCY": Config.DIRICHLET_NTK_BALANCE_FREQUENCY,
        "DIRICHLET_NTK_BLEND": Config.DIRICHLET_NTK_BLEND,
        "LEFT_DIRICHLET_LOSS_MIN_MULTIPLIER": Config.LEFT_DIRICHLET_LOSS_MIN_MULTIPLIER,
        "LEFT_DIRICHLET_LOSS_MAX_MULTIPLIER": Config.LEFT_DIRICHLET_LOSS_MAX_MULTIPLIER,
        "RIGHT_DIRICHLET_LOSS_MIN_MULTIPLIER": Config.RIGHT_DIRICHLET_LOSS_MIN_MULTIPLIER,
        "RIGHT_DIRICHLET_LOSS_MAX_MULTIPLIER": Config.RIGHT_DIRICHLET_LOSS_MAX_MULTIPLIER,
        "CURVATURE_REG_WEIGHT": Config.CURVATURE_REG_WEIGHT,
        "ENABLE_PHYSICS_POLISH": Config.ENABLE_PHYSICS_POLISH,
        "PHYSICS_POLISH_ITERS": Config.PHYSICS_POLISH_ITERS,
        "PHYSICS_POLISH_MAX_ROUNDS": Config.PHYSICS_POLISH_MAX_ROUNDS,
        "PHYSICS_POLISH_TARGET_PDE_MEAN": Config.PHYSICS_POLISH_TARGET_PDE_MEAN,
        "PHYSICS_POLISH_TARGET_PDE_MAX": Config.PHYSICS_POLISH_TARGET_PDE_MAX,
        "PHYSICS_POLISH_PDE_FACTOR": Config.PHYSICS_POLISH_PDE_FACTOR,
        "PHYSICS_POLISH_DIR_FACTOR": Config.PHYSICS_POLISH_DIR_FACTOR,
        "PHYSICS_POLISH_NEU_FACTOR": Config.PHYSICS_POLISH_NEU_FACTOR,
        "PHYSICS_POLISH_DATA_FACTOR": Config.PHYSICS_POLISH_DATA_FACTOR,
        "PHYSICS_POLISH_CURV_FACTOR": Config.PHYSICS_POLISH_CURV_FACTOR,
        "PDE_WARMUP_EPOCHS": Config.PDE_WARMUP_EPOCHS,
        "PDE_WARMUP_START_FACTOR": Config.PDE_WARMUP_START_FACTOR,
        "ENABLE_RAR": Config.ENABLE_RAR,
        "RAR_START_EPOCH": Config.RAR_START_EPOCH,
        "RAR_FREQUENCY": Config.RAR_FREQUENCY,
        "RAR_REPLACE_FRACTION": Config.RAR_REPLACE_FRACTION,
        "RAR_CANDIDATE_MULTIPLIER": Config.RAR_CANDIDATE_MULTIPLIER,
        "RAR_CORNER_FRACTION": Config.RAR_CORNER_FRACTION,
        "RAR_CORNER_BAND_FRACTION": Config.RAR_CORNER_BAND_FRACTION,
        "RAR_LEFT_FRACTION": Config.RAR_LEFT_FRACTION,
        "RAR_LEFT_BAND_FRACTION": Config.RAR_LEFT_BAND_FRACTION,
        "RAR_RIGHT_FRACTION": Config.RAR_RIGHT_FRACTION,
        "RAR_RIGHT_BAND_FRACTION": Config.RAR_RIGHT_BAND_FRACTION,
        "PDE_RESIDUAL_ND_MEAN_THRESHOLD": Config.PDE_RESIDUAL_ND_MEAN_THRESHOLD,
        "PDE_RESIDUAL_ND_MAX_THRESHOLD": Config.PDE_RESIDUAL_ND_MAX_THRESHOLD,
        "RELATIVE_L2_THRESHOLD": Config.RELATIVE_L2_THRESHOLD,
        "BOUNDARY_BC_ND_THRESHOLD": Config.BOUNDARY_BC_ND_THRESHOLD,
        "BOUNDARY_BC_THRESHOLD": Config.BOUNDARY_BC_THRESHOLD,
        "FALSE_CONV_LOSS_THRESHOLD": Config.FALSE_CONV_LOSS_THRESHOLD,
        "FALSE_CONV_PDE_ND_THRESHOLD": Config.FALSE_CONV_PDE_ND_THRESHOLD,
        "FALSE_CONV_PDE_GROWTH_THRESHOLD": Config.FALSE_CONV_PDE_GROWTH_THRESHOLD,
        "TUNING_W_REL_L2": Config.TUNING_W_REL_L2,
        "TUNING_W_PDE_RESIDUAL": Config.TUNING_W_PDE_RESIDUAL,
        "TUNING_W_BOUNDARY_BC": Config.TUNING_W_BOUNDARY_BC,
        "DOMAIN_SIZE": Config.DOMAIN_SIZE,
        "LX": Config.LX,
        "LY": Config.LY,
        "T_LEFT": Config.T_LEFT,
        "T_RIGHT": Config.T_RIGHT,
    }

    try:
        yield Config
    finally:
        for key, value in tracked.items():
            setattr(Config, key, value)

